version: '3.8'

services:
  traefik:
    image: traefik:v3.3.6
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:44380"
      - "--entrypoints.dashboard.http.tls=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--certificatesresolvers.myresolver.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.myresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=infogerance@eenov.com"
      - "--accesslog=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.minesword.fr`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.priority=3"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$2b$$12$$g/DlTyqldxnUMMp7gqqG3.IvFYhUF2uVcp/I6BL6KV8Ny2ik.PxMq"
      - "traefik.http.routers.dashboard.middlewares=auth"
    ports:
      - "80:80"
      - "443:443"
      - "44380:44380"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./acme:/acme"
    restart: always
    networks:
      - notes-network

  frontend:
    image: ghcr.io/takenotes-app/notes-frontend:latest
    container_name: notes-frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`notes.minesword.fr`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.routers.frontend.tls=true"
    networks:
      - notes-network

  backend:
    image: ghcr.io/takenotes-app/notes-backend:latest
    container_name: notes-backend
    restart: always
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://admin:$MONGO_PASSWORD@notes-mongo:27017/admin?authSource=admin
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - notes-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`notes.minesword.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.priority=2"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  mongo:
    image: mongo:8.0
    container_name: notes-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    networks:
      - notes-network
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: [
        "CMD-SHELL",
        "mongosh --username admin --password \"$MONGO_PASSWORD\" --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  notes-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
