name: Build and Push Frontend to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Required for GHCR access
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout frontend
      uses: actions/checkout@v4
      with:
        repository: takeNotes-app/notes-app
        path: ./notes-app

    - name: Checkout backend
      uses: actions/checkout@v4
      with:
        repository: takeNotes-app/notes-app-backend
        path: ./notes-app-backend

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Frontend
      id: meta-frontend
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/takeNotes-app/notes-frontend
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=sha,format=short

    - name: Extract metadata for Backend
      id: meta-backend
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/takeNotes-app/notes-backend
        tags: |
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=sha,format=short

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./notes-app
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./notes-app-backend
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  pull-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            echo 'Pulling latest images from GHCR...'
            # Use sudo for Docker commands
            sudo docker pull ghcr.io/takenotes-app/notes-frontend:latest
            
            echo 'Deploying with Docker Compose...'
            cd /home/${{ secrets.SSH_USER }}
            # Use sudo for docker-compose commands
            sudo -E docker compose pull
            sudo -E docker compose up -d --force-recreate
            
            echo 'Deployment complete. Checking container status...'
            sudo docker ps
          "